app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

#HWIOAuthBundle routes
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /secured/connect

facebook_login:
    path: /secured/login_facebook


my_login:
    path:      /login
    defaults:  { _controller: MyUserBundle:Security:login, _method: POST GET }

my_login_check:
    path:      /login_check
    defaults:  { _controller: MyUserBundle:Security:check, _method: POST }

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"


negocio_logout:
    path: /negocio/logout